// <auto-generated />
using System;
using Fateblade.Haushaltsbuch.Data.DataStoring.SqLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fateblade.Haushaltsbuch.Data.DataStoring.SqLite.Migrations.BillSqLiteRepositoryMigrations
{
    [DbContext(typeof(BillSqLiteRepository))]
    [Migration("20190912213500_InitialBills")]
    partial class InitialBills
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Fateblade.Haushaltsbuch.CrossCutting.DataClasses.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoughtAtSourceId");

                    b.Property<DateTime>("BuyDate");

                    b.Property<string>("Note");

                    b.Property<decimal>("SumPaid");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
