// <auto-generated />
using Fateblade.Haushaltsbuch.Data.DataStoring.SqLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fateblade.Haushaltsbuch.Data.DataStoring.SqLite.Migrations.ItemSqLiteRepositoryMigrations
{
    [DbContext(typeof(ItemSqLiteRepository))]
    partial class ItemSqLiteRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Fateblade.Haushaltsbuch.CrossCutting.DataClasses.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Note");

                    b.Property<decimal>("PricePerUnit");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
