// <auto-generated />
using Fateblade.Haushaltsbuch.Data.DataStoring.SqLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fateblade.Haushaltsbuch.Data.DataStoring.SqLite.Migrations.SourceSqLiteRepositoryMigrations
{
    [DbContext(typeof(SourceSqLiteRepository))]
    [Migration("20190912123820_InitialSources")]
    partial class InitialSources
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Fateblade.Haushaltsbuch.CrossCutting.DataClasses.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
